version: '3.2'

networks:
  expense-network:

services:
  expense:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD:/go/src/target
    depends_on:
      - db
    networks:
      - expense-network
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expenses
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - expense-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - expense-network
    depends_on:
      - db